baseurl = "."
languageCode = "en-us"
title = "Notebook"
theme = "hyde"

[params]
  themeColor = "theme-base-09"
  
  
  
[menu]

  [[menu.blogs]]
    identifier = "blogs"
    name = "blogs"
    title = "blogs"
    url = "/blogs/"
    weight = -110

 [[menu.posts]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/posts/"
    weight = -110
